[settings]
activate_aggressive = true
experimental = true

[settings.python]
uv_venv_auto = true

[env]
_.path = './bin'

[tools]
gum = "latest"
hk = "latest"
pkl = "latest"
shellcheck = "latest"
shfmt = "latest"
skate = "latest"

[hooks]
postinstall = { task = "bootstrap" }

[tasks.bootstrap]
run = [
  "hk install --mise",
  { task = "update-hk-import" },
  "brew bundle install",
]

[tasks.update]
alias = ["upd"]
run = ["mise upgrade", { task = "update-hk-import" }, "brew bundle upgrade"]

[tasks.upgrade]
alias = ["upg"]
run = [
  "mise upgrade --bump",
  { task = "update-hk-import" },
  "brew bundle upgrade",
]

[tasks.update-hk-import]
run = "scripts/update-hk-import.bash"

[tasks.check]
alias = ["chk", "lint"]
run = "hk check --all"

[tasks.fix]
alias = ["format"]
run = "hk fix --all"
